site_name: My Docs
nav:
- 首页: index.md
- About: about.md
theme: 
  name: material
  palette:
  - scheme: default
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - scheme: slate
    toggle:
      icon: material/weather-night
      name: Swith to light mode

  media: "(prefers-color-scheme: light)"