site_name: Harudog's Note
site_description: Harudog's Learning Note and His Learning Resources
site_author: Harudog, the happy puppy

theme: 
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Roboto
  features:
    - navigation.sidebar
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    # - navigation.expand


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition  # 基本 admonition 支持
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
  - footnotes
  - pymdownx.blocks.admonition  # 添加这个扩展来支持 [!note] 语法

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: Copyright &copy; 2025 - 2030 Not a real copyright

# Navigation Part

nav:
  - 首页: index.md
  - 微观经济: 
    - 微观经济学导入: microeco/tutorial1.md
    - 消费者理论一: microeco/tutorial2.md
    - 消费者理论二: microeco/tutorial3.md
    - 消费者理论三: microeco/tutorial4.md
    - 消费者理论四: microeco/tutorial5.md
    - 消费者理论与市场: microeco/tutorial6.md

  - 金融学:
    - 金融导论: finance/finance1.md
    - 金融货币: finance/finance2.md
    - 金融外汇: finance/finance3.md
    - 金融信用: finance/finance4.md
    - 利息利率: finance/finance5.md
  - About: about.md